/**
 * If Twitter oAuth fails for some reason,
 * just return this "saved" data grabbed from previous successful request
 * @type {Array}
 */

var dummyData = [
	{"created_at": "Dummy Wed Aug 07 10:26:43 +0000 2013", "id": 365056404022759400, "id_str": "365056404022759427", "text": "Mobile In Brazil, India And China — Tracking The Next Massive Growth Wave In Smartphones http://t.co/R6EJ4osD9N via @sai", "source": "<a href=\"http://twitter.com/tweetbutton\" rel=\"nofollow\">Tweet Button</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/R6EJ4osD9N", "expanded_url": "http://www.businessinsider.com/mobile-in-china-india-and-emerging-markets-2013-8", "display_url": "businessinsider.com/mobile-in-chin…", "indices": [89, 111]}
	], "user_mentions": [
		{"screen_name": "SAI", "name": "BI: Tech", "id": 8841372, "id_str": "8841372", "indices": [116, 120]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Mon Aug 05 12:46:08 +0000 2013", "id": 364366714072346600, "id_str": "364366714072346627", "text": "New vacancy opened up! Ciklum is looking for QA Team Lead to join our Playtech team - See more at: http://t.co/A0rrFJbzCg", "source": "web", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/A0rrFJbzCg", "expanded_url": "http://bit.ly/17txqHQ", "display_url": "bit.ly/17txqHQ", "indices": [99, 121]}
	], "user_mentions": []}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Thu Aug 01 12:28:27 +0000 2013", "id": 362912710440132600, "id_str": "362912710440132608", "text": "Heroes and zeroes: Tech's best and worst of 2013 (so far) http://t.co/DWh2H8DB6b via @infoworld", "source": "<a href=\"http://sharethis.com\" rel=\"nofollow\">ShareThis.com</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/DWh2H8DB6b", "expanded_url": "http://shar.es/kLZqm", "display_url": "shar.es/kLZqm", "indices": [58, 80]}
	], "user_mentions": [
		{"screen_name": "infoworld", "name": "infoworld", "id": 15426758, "id_str": "15426758", "indices": [85, 95]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Wed Jul 31 14:53:40 +0000 2013", "id": 362586865821421600, "id_str": "362586865821421570", "text": "10 cutting-edge mobile development tools http://t.co/h3ysxG7Pug via @infoworld", "source": "<a href=\"http://sharethis.com\" rel=\"nofollow\">ShareThis.com</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/h3ysxG7Pug", "expanded_url": "http://shar.es/kVTUa", "display_url": "shar.es/kVTUa", "indices": [41, 63]}
	], "user_mentions": [
		{"screen_name": "infoworld", "name": "infoworld", "id": 15426758, "id_str": "15426758", "indices": [68, 78]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Wed Jul 31 14:20:43 +0000 2013", "id": 362578577427922940, "id_str": "362578577427922944", "text": "8 Best iTunes Alternatives http://t.co/QA5trIg124 via @mashable", "source": "<a href=\"http://twitter.com/tweetbutton\" rel=\"nofollow\">Tweet Button</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/QA5trIg124", "expanded_url": "http://on.mash.to/1e97rZU", "display_url": "on.mash.to/1e97rZU", "indices": [27, 49]}
	], "user_mentions": [
		{"screen_name": "mashable", "name": "Mashable", "id": 972651, "id_str": "972651", "indices": [54, 63]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Wed Jul 31 07:00:28 +0000 2013", "id": 362467782350217200, "id_str": "362467782350217217", "text": "JUST EAT Group Chooses Ciklum as a Strategic Software Development Partner http://t.co/kSathCxPVM", "source": "<a href=\"http://www.prweb.com\" rel=\"nofollow\">PRWeb</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 2, "favorite_count": 1, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/kSathCxPVM", "expanded_url": "http://bit.ly/12Zq5yy", "display_url": "bit.ly/12Zq5yy", "indices": [74, 96]}
	], "user_mentions": []}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Tue Jul 30 12:27:51 +0000 2013", "id": 362187786004074500, "id_str": "362187786004074500", "text": "RT @boostagile: Agile Project Management is Not Just About Iterative Delivery and Stand-ups. - http://t.co/V0KVzvkDsZ #agile #enterprise", "source": "web", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweeted_status": {"created_at": "Mon Jul 29 21:44:33 +0000 2013", "id": 361965492208021500, "id_str": "361965492208021504", "text": "Agile Project Management is Not Just About Iterative Delivery and Stand-ups. - http://t.co/V0KVzvkDsZ #agile #enterprise", "source": "<a href=\"http://bufferapp.com\" rel=\"nofollow\">Buffer</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 293298892, "id_str": "293298892", "name": "Boost Agile", "screen_name": "boostagile", "location": "Shanghai, China", "description": "Based in #Shanghai, #China. Interested in #scrum, #agile, #webdevelopment and more", "url": "http://t.co/zrAAzEWJke", "entities": {"url": {"urls": [
		{"url": "http://t.co/zrAAzEWJke", "expanded_url": "http://www.boostagile.com", "display_url": "boostagile.com", "indices": [0, 22]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 9691, "friends_count": 61, "listed_count": 15, "created_at": "Thu May 05 03:11:31 +0000 2011", "favourites_count": 0, "utc_offset": 43200, "time_zone": "Wellington", "geo_enabled": false, "verified": false, "statuses_count": 635, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "EBEBEB", "profile_background_image_url": "http://a0.twimg.com/images/themes/theme7/bg.gif", "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme7/bg.gif", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/3633399261/974fab8e2be38262314982fc51e68865_normal.png", "profile_image_url_https": "https://si0.twimg.com/profile_images/3633399261/974fab8e2be38262314982fc51e68865_normal.png", "profile_link_color": "990000", "profile_sidebar_border_color": "DFDFDF", "profile_sidebar_fill_color": "F3F3F3", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 3, "favorite_count": 1, "entities": {"hashtags": [
		{"text": "agile", "indices": [102, 108]},
		{"text": "enterprise", "indices": [109, 120]}
	], "symbols": [], "urls": [
		{"url": "http://t.co/V0KVzvkDsZ", "expanded_url": "http://j.mp/16w6VT5", "display_url": "j.mp/16w6VT5", "indices": [79, 101]}
	], "user_mentions": []}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"}, "retweet_count": 3, "favorite_count": 0, "entities": {"hashtags": [
		{"text": "agile", "indices": [118, 124]},
		{"text": "enterprise", "indices": [125, 136]}
	], "symbols": [], "urls": [
		{"url": "http://t.co/V0KVzvkDsZ", "expanded_url": "http://j.mp/16w6VT5", "display_url": "j.mp/16w6VT5", "indices": [95, 117]}
	], "user_mentions": [
		{"screen_name": "boostagile", "name": "Boost Agile", "id": 293298892, "id_str": "293298892", "indices": [3, 14]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Tue Jul 30 11:00:54 +0000 2013", "id": 362165901988077600, "id_str": "362165901988077568", "text": "Should core software development move off-shore to a “cloud”? The case for Israeli hi-tech http://t.co/Ow2aZCb35w via @sharethis", "source": "<a href=\"http://twitter.com/tweetbutton\" rel=\"nofollow\">Tweet Button</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/Ow2aZCb35w", "expanded_url": "http://shar.es/kFUnJ", "display_url": "shar.es/kFUnJ", "indices": [91, 113]}
	], "user_mentions": [
		{"screen_name": "ShareThis", "name": "ShareThis", "id": 14116807, "id_str": "14116807", "indices": [118, 128]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Mon Jul 29 12:00:19 +0000 2013", "id": 361818465968984060, "id_str": "361818465968984065", "text": "10 Highest Paying IT Careers for 2013 http://t.co/uqQIu3PJTo via @CIOonline", "source": "<a href=\"http://sharethis.com\" rel=\"nofollow\">ShareThis.com</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 2, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/uqQIu3PJTo", "expanded_url": "http://shar.es/kOOto", "display_url": "shar.es/kOOto", "indices": [38, 60]}
	], "user_mentions": [
		{"screen_name": "CIOonline", "name": "CIO.com", "id": 22873424, "id_str": "22873424", "indices": [65, 75]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Thu Jul 25 08:40:17 +0000 2013", "id": 360318574402863100, "id_str": "360318574402863106", "text": "10 Big Data Trends Changing the Face of Business http://t.co/CQOYqC3u89 via @CIOonline", "source": "<a href=\"http://sharethis.com\" rel=\"nofollow\">ShareThis.com</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/CQOYqC3u89", "expanded_url": "http://shar.es/kJIaL", "display_url": "shar.es/kJIaL", "indices": [49, 71]}
	], "user_mentions": [
		{"screen_name": "CIOonline", "name": "CIO.com", "id": 22873424, "id_str": "22873424", "indices": [76, 86]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Wed Jul 24 11:27:01 +0000 2013", "id": 359998145742127100, "id_str": "359998145742127105", "text": "RT @Developer_Tech: Google's holding a (slightly) mysterious \"Breakfast with Sundar Pichai\" event. What do we expect? http://t.co/aWjr0NSs2…", "source": "web", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweeted_status": {"created_at": "Wed Jul 24 11:20:38 +0000 2013", "id": 359996541257252860, "id_str": "359996541257252865", "text": "Google's holding a (slightly) mysterious \"Breakfast with Sundar Pichai\" event. What do we expect? http://t.co/aWjr0NSs2l #Android", "source": "<a href=\"http://twitter.com/tweetbutton\" rel=\"nofollow\">Tweet Button</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 281032444, "id_str": "281032444", "name": "Developer Tech", "screen_name": "Developer_Tech", "location": "Bristol, London", "description": "Developer News, Jobs & SDK Coding Insight: App Development Software, iOS, Android, Windows, .net,  App Store, Platform, Hacking, HTML5, PHP, J2ME, 3D, CMS, Ajax", "url": "http://t.co/tkFWShSfbP", "entities": {"url": {"urls": [
		{"url": "http://t.co/tkFWShSfbP", "expanded_url": "http://www.developer-tech.com/", "display_url": "developer-tech.com", "indices": [0, 22]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 846, "friends_count": 1151, "listed_count": 35, "created_at": "Tue Apr 12 13:58:10 +0000 2011", "favourites_count": 0, "utc_offset": null, "time_zone": null, "geo_enabled": false, "verified": false, "statuses_count": 715, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "E7E7E6", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/285122229/developerbackground.jpg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/285122229/developerbackground.jpg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1387004480/dt-twitter-icon_normal.gif", "profile_image_url_https": "https://si0.twimg.com/profile_images/1387004480/dt-twitter-icon_normal.gif", "profile_link_color": "0084B4", "profile_sidebar_border_color": "C0DEED", "profile_sidebar_fill_color": "DDEEF6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 2, "favorite_count": 0, "entities": {"hashtags": [
		{"text": "Android", "indices": [121, 129]}
	], "symbols": [], "urls": [
		{"url": "http://t.co/aWjr0NSs2l", "expanded_url": "http://bit.ly/15fmqzw", "display_url": "bit.ly/15fmqzw", "indices": [98, 120]}
	], "user_mentions": []}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"}, "retweet_count": 2, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/aWjr0NSs2", "expanded_url": "http://t.co/aWjr0NSs2", "display_url": "t.co/aWjr0NSs2", "indices": [118, 139]}
	], "user_mentions": [
		{"screen_name": "Developer_Tech", "name": "Developer Tech", "id": 281032444, "id_str": "281032444", "indices": [3, 18]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Tue Jul 23 11:59:12 +0000 2013", "id": 359643859547996160, "id_str": "359643859547996161", "text": "@Roadnet shares its software development cooperation with Ciklum http://t.co/fucSud9YZz", "source": "web", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": 43196501, "in_reply_to_user_id_str": "43196501", "in_reply_to_screen_name": "Roadnet", "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/fucSud9YZz", "expanded_url": "http://bit.ly/18x8LFe", "display_url": "bit.ly/18x8LFe", "indices": [65, 87]}
	], "user_mentions": [
		{"screen_name": "Roadnet", "name": "Roadnet Technologies", "id": 43196501, "id_str": "43196501", "indices": [0, 8]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Fri Jul 19 10:55:49 +0000 2013", "id": 358178355180351500, "id_str": "358178355180351490", "text": "Swiss companies name reliability as top criterion when choosing outsourcing-partners. Read more here http://t.co/O0ubfQoCL4", "source": "web", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/O0ubfQoCL4", "expanded_url": "http://bit.ly/1buWJQD", "display_url": "bit.ly/1buWJQD", "indices": [101, 123]}
	], "user_mentions": []}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Thu Jul 18 11:57:07 +0000 2013", "id": 357831394581426200, "id_str": "357831394581426176", "text": "Hiring: Ciklum is looking for Node.JS developer to join our @economicdk team. See more at http://t.co/OuPuddSF1O", "source": "web", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 2, "favorite_count": 1, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/OuPuddSF1O", "expanded_url": "http://bit.ly/11ZypDh", "display_url": "bit.ly/11ZypDh", "indices": [90, 112]}
	], "user_mentions": [
		{"screen_name": "economicdk", "name": "e-conomic danmark", "id": 92962378, "id_str": "92962378", "indices": [60, 71]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Thu Jul 18 09:03:41 +0000 2013", "id": 357787748976951300, "id_str": "357787748976951298", "text": "Tumblr updates its iOS app with ‘very important’ security fix, asks users to change passwords http://t.co/zYDViFN4Lw via @TNWapps", "source": "<a href=\"http://twitter.com/tweetbutton\" rel=\"nofollow\">Tweet Button</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/zYDViFN4Lw", "expanded_url": "http://tnw.to/s6IC", "display_url": "tnw.to/s6IC", "indices": [94, 116]}
	], "user_mentions": [
		{"screen_name": "TNWapps", "name": "TNW Apps", "id": 83493074, "id_str": "83493074", "indices": [121, 129]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Wed Jul 17 14:02:01 +0000 2013", "id": 357500441552101400, "id_str": "357500441552101377", "text": "Why It's Suddenly Impossible To Buy An iPhone In Russia http://t.co/CWH8NSPIfD via @sai", "source": "<a href=\"http://twitter.com/tweetbutton\" rel=\"nofollow\">Tweet Button</a>", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 1, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/CWH8NSPIfD", "expanded_url": "http://www.businessinsider.com/in-russia-iphone-buys-you-2013-7", "display_url": "businessinsider.com/in-russia-ipho…", "indices": [56, 78]}
	], "user_mentions": [
		{"screen_name": "SAI", "name": "BI: Tech", "id": 8841372, "id_str": "8841372", "indices": [83, 87]}
	]}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Tue Jul 16 12:52:00 +0000 2013", "id": 357120430403887100, "id_str": "357120430403887105", "text": "Do you know how #CloudComputing solutions can help businesses solve the problems they can't solve on their own? http://t.co/q2HaXVyHVN", "source": "web", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [
		{"text": "CloudComputing", "indices": [16, 31]}
	], "symbols": [], "urls": [
		{"url": "http://t.co/q2HaXVyHVN", "expanded_url": "http://bit.ly/12twpOt", "display_url": "bit.ly/12twpOt", "indices": [112, 134]}
	], "user_mentions": []}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"},
	{"created_at": "Tue Jul 16 09:09:20 +0000 2013", "id": 357064395500683260, "id_str": "357064395500683265", "text": "ISV Innovation in the Cloud Economy | CIKLUM BLOG http://t.co/q2HaXVyHVN", "source": "web", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/q2HaXVyHVN", "expanded_url": "http://bit.ly/12twpOt", "display_url": "bit.ly/12twpOt", "indices": [50, 72]}
	], "user_mentions": []}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "sl"},
	{"created_at": "Mon Jul 15 12:31:21 +0000 2013", "id": 356752845334253600, "id_str": "356752845334253569", "text": "Ciklum Sponsors MMA Mobile Gaming UK 2013 http://t.co/o3eCLmFL71", "source": "web", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/o3eCLmFL71", "expanded_url": "http://bit.ly/18b8YBu", "display_url": "bit.ly/18b8YBu", "indices": [42, 64]}
	], "user_mentions": []}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "pl"},
	{"created_at": "Thu Jul 11 13:00:04 +0000 2013", "id": 355310523815952400, "id_str": "355310523815952385", "text": "Do you know how gamers can monetise, acquire and retain using mobile marketing? We do! http://t.co/o3eCLmFL71", "source": "web", "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 30045349, "id_str": "30045349", "name": "Ciklum", "screen_name": "ciklum", "location": "worldwide", "description": "Danish IT outsourcing services provider in Ukraine, Belarus, Pakistan. Tweeting about Agile software development,  IT job openings, high-tech news & events...", "url": "http://t.co/P7y0SnFM", "entities": {"url": {"urls": [
		{"url": "http://t.co/P7y0SnFM", "expanded_url": "http://www.ciklum.com", "display_url": "ciklum.com", "indices": [0, 20]}
	]}, "description": {"urls": []}}, "protected": false, "followers_count": 1741, "friends_count": 802, "listed_count": 51, "created_at": "Thu Apr 09 19:12:58 +0000 2009", "favourites_count": 8, "utc_offset": 10800, "time_zone": "Kyiv", "geo_enabled": true, "verified": false, "statuses_count": 3812, "lang": "en", "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF8308", "profile_background_image_url": "http://a0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/378800000040930396/72f774a4f77950667db6810c96305faa.jpeg", "profile_background_tile": false, "profile_image_url": "http://a0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_image_url_https": "https://si0.twimg.com/profile_images/1554594169/Logo_Ciklum_Empowering_Collaboration_180by180_normal.jpg", "profile_link_color": "FF8308", "profile_sidebar_border_color": "FFFFFF", "profile_sidebar_fill_color": "F6F6F6", "profile_text_color": "333333", "profile_use_background_image": true, "default_profile": false, "default_profile_image": false, "following": null, "follow_request_sent": false, "notifications": null}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweet_count": 0, "favorite_count": 0, "entities": {"hashtags": [], "symbols": [], "urls": [
		{"url": "http://t.co/o3eCLmFL71", "expanded_url": "http://bit.ly/18b8YBu", "display_url": "bit.ly/18b8YBu", "indices": [87, 109]}
	], "user_mentions": []}, "favorited": false, "retweeted": false, "possibly_sensitive": false, "lang": "en"}
];

dummyData = JSON.stringify(dummyData);

exports.data = dummyData;
